# Generated by Django 6.0.4 on 2026-04-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_chapter_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PENDING_TITLE', 'Pending Title'), ('TITLE_APPROVED', 'Title Approved'), ('TITLE_REJECTED', 'Title Rejected'), ('SUPERVISOR_ASSIGNED', 'Supervisor Assigned'), ('IN_PROGRESS', 'In Progress'), ('UNDER_REVIEW', 'Under Review'), ('COMPLETED', 'Completed')], default='PENDING_TITLE', max_length=25),
        ),
    ]
