# Generated by Django 6.0.4 on 2026-04-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_chapter_options_chapter_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
